name: NickLaparra
favicon: null
layout_spectrum: 0.1571283540688455
typography_spectrum: 0.29354782681912184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.778272365918383
  lightness: 0.21361602400429547
  saturation: 0.4721141057088971
  rhythmicContrast: 0.869566464331001
purpose: []
