name: NickLaparra
favicon: null
layout_spectrum: 0.1571283540688455
typography_spectrum: 0.29354782681912184
title: Nick Laparra
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404044'
    - '#7c816d'
    - '#eee6d7'
    - '#acaf9c'
    - '#dcc895'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.4721141057088971
  rhythmicContrast: 0.75
purpose: []
