name: NickLaparra
favicon: null
layout_spectrum: 0.75359
typography_spectrum: 0.75592
title: Nick Laparra
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#343434'
    - '#909090'
    - '#d7d7d7'
    - '#b5b5b5'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.4721141057088971
  rhythmicContrast: 0.75
purpose: []
